application: spojrec
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  script: site/rec.py
  
- url: /helloworld
  script: helloworld.py
  
- url: /compmetricsstart
  script: recommender/compmetricsJob.py

- url: /testrec
  script: recommender/testrec.py
  
- url: /crawnspojstart
  script: crawler/crawnSpojJob.py
  
- url: /urldownloader
  script: crawler/urlDownloaderJob.py
  
- url: /(.*\.(gif|png|jpg|ico))$
  static_files: img/\1
  upload: img/.*\.(gif|png|jpg|ico)$
  
- url: /style\.css
  mime_type: text/css
  static_files: style.css
  upload: style.css


libraries:
- name: lxml
  version: "2.3"